[package]
name = "artillery-only"
version = "0.1.0"
authors = ["JJendryka <jendryka.j@gmail.com>"]
edition='2018'

[lib]
name = "artillery_only"

[dependencies]
enet = "0.2.0"
serde = "1.0.80"
piston2d-graphics = "0.28.0"
bit-vec = "0.5.0"
